baseurl = "http://ricardoillescas.com"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "ricardoillescas.com"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Ricardo Illescas" # Set a different text for the header on the home page
  subtitle = "Software Engineer + Game Developer"
  #logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "2 January, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Ricardo Illescas"
  website = "ricardoillescas.com"
  email = "hello@ricardoillescas.com"
  facebook = "rik.illescas"
  github = "riktothepast"
  bitbucket = "riktothepast"
  twitter = "riktothepast"
  linkedin = "rik-illescas-00995814b"
  spotify = "riktothepast"
  itchio = "riktothepast"

[[menu.main]]
    name = "Blog"
    url = "blog"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
